set_vicare_mode:
  name: Set vicare mode
  description: Set a ViCare mode.
  target:
    entity:
      integration: vicare
      domain: climate
  fields:
    vicare_mode:
      name: Vicare Mode
      description: ViCare mode.
      required: true
      selector:
        select:
          options:
            - "dhw"
            - "dhwAndHeating"
            - "dhwAndHeatingCooling"
            - "forcedNormal"
            - "forcedReduced"
            - "heating"
            - "standby"

set_heating_curve:
  name: Set Vicare Heating Curve
  description: Set Vicare Heating Curve.
  target:
    entity:
      integration: vicare
      domain: climate
  fields:
    shift:
      name: Vicare Heating Curve Shift
      description: Vicare Heating Curve Shift
      required: true
      selector:
        number:
          min: -13
          max: 40
    slope:
      name: Vicare Heating Curve Slope
      description: Vicare Heating Curve Slope
      required: true
      selector:
        number:
          min: 0.2
          max: 3.5